### ISSUE TITLE
JSON translation files don't seem to be included in the export

### ISSUE THREAD

**Issue by nkeena** [kg-bot/laravel-localization-to-vue#19]
I have a `es.json` file in the lang root directory as per [Laravel documentation](https://laravel.com/docs/5.7/localization#using-translation-strings-as-keys). I chose this option since I have a lot of translation strings.

But the export function (including artisan command) only parses `.php` files. Any ideas on how to get the translations in the `.json` files included?

**Comment by subotkevic** [comment]
@nkeena you can try my package for translation exporting into `json` files, it's very simple:
[Laravel JSON Translation Helper](https://github.com/subotkevic/laravel-json-translation-helper)

**Comment by sentiasa** [comment]
Hey @kg-bot, any updates on this? I want to use `.json` file also but couldn't find it in docs :(
