### ISSUE TITLE
Error with to toFlat

### ISSUE THREAD

**Issue by ibrahemhamdy1** [kg-bot/laravel-localization-to-vue#28]
![screenshot_12](https://user-images.githubusercontent.com/25735311/50478303-1f592580-09d9-11e9-909c-876da194f636.png)

**Comment by ibrahemhamdy1** [comment]
Ok, I will.

**Comment by ibrahemhamdy1** [comment]
Check the pull request, please.

**Comment by sasokovacic** [comment]
still having the same problem.. I don't have the fix in the ExportLocalizations.php file...
I installed the latest version of your plugin...

**Comment by sasokovacic** [comment]
thanks it works
