### ISSUE TITLE
Integration with Spatie Laravel Translation Loader

### ISSUE THREAD

**Issue by cyberfly** [kg-bot/laravel-localization-to-vue#38]
Hi how to integrate this package with Spatie Laravel Translation Loader? [https://github.com/spatie/laravel-translation-loader](https://github.com/spatie/laravel-translation-loader)

Spatie package allow me to store language key in database, by overriding the Service Provider 

![image](https://user-images.githubusercontent.com/1756170/54182047-5b316080-44db-11e9-9459-1321c4875c80.png)

Thanks

**Comment by alexhackney** [comment]
Was this completed? I dont see any mention of it in the docs.
