### ISSUE TITLE
Trans.get not working

### ISSUE THREAD

**Issue by mstaroste** [kg-bot/laravel-localization-to-vue#40]
Hello,

I think there is an error. Your code forms all language files as a json string. With locale attribute and translate files and values.
The lang.js needs the data as a json object as well but locale is part of the attribute e.g. "en.greetings"
`var lang = new Lang({
    messages: {
        'en.greetings': {
            'hi': 'Hi',
            'hello': 'Hello'
        },
        'it.greetings': {
            'hi': 'Salve'
        }
    }
});`

**Comment by JValck** [comment]
How do you retrieve the json?
If it is via the  provided route, then use a workaround as the provided route returns `toArray`instead of `toFlat`.
See [here](https://github.com/kg-bot/laravel-localization-to-vue/blob/master/src/routes.php#L15)
