### ISSUE TITLE
ErrorException: get_object_vars() expects parameter 1 to be object, array given

### ISSUE THREAD

**Issue by rafatga** [kg-bot/laravel-localization-to-vue#42]
Hi,
I would like to know if I am the only one getting this error.

**Version**
"kg-bot/laravel-localization-to-vue": "^1.6"

![Captura de pantalla de 2019-09-02 08-35-30](https://user-images.githubusercontent.com/3813277/64094790-2355f800-cd5d-11e9-80d8-729f9b7964e2.png)
![Captura de pantalla de 2019-09-02 08-37-22](https://user-images.githubusercontent.com/3813277/64094796-25b85200-cd5d-11e9-9072-488d3ba00cf1.png)

**Comment by hi-rafa** [comment]
When I delete this following two files it wroks again.

![Captura de pantalla de 2019-09-02 08-51-46](https://user-images.githubusercontent.com/3813277/64095406-002c4800-cd5f-11e9-8caa-cec43e0dd018.png)

**Comment by KubqoA** [comment]
Thanks, adding the `en.json` file seems to have resolved the issue for me. Sorry for bothering.
