### ISSUE TITLE
Add Laravel 8 and 9 support

### ISSUE THREAD

**Issue by dhi2** [kg-bot/laravel-localization-to-vue#65]
Please add support for Laravel 8 and 9.

**Comment by psxx** [comment]
Hi,

Have you been able to look at the changes? I quickly look at your code and it seems like L8 won't affect it.
Huge changes were made in queues and seeds/factories.

Seems like just version bump will do just fine. What do you think?

**Comment by psxx** [comment]
Hi,

Since I rely on this package please check: https://github.com/kg-bot/laravel-localization-to-vue/pull/67

Best,
