### ISSUE TITLE
New version with Laravel 10 support

### ISSUE THREAD

**Issue by bally86** [kg-bot/laravel-localization-to-vue#87]
Can you please create a new release with the Laravel 10 support in it?

**Comment by blackjak231** [comment]
@kg-bot Do you at least have a release date in mind ?

**Comment by bally86** [comment]
> Today or tomorrow I hope since there's no breaking changes in the latest pull requests that were merged.

Any news?

**Comment by bally86** [comment]
Do you have a new release date in mind?
